version: '3.9'

services:
  db:
    image: postgres
    container_name: etl_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ~/apps/etl_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${ETL_PASSWORD}
      - POSTGRES_USER=${ETL_USER}
      - POSTGRES_DB=etl_db

  airflow:
    image: apache/airflow
    container_name: etl_airflow
    environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${ETL_USER}:${ETL_PASSWORD}@etl_db:5432/etl_db
    - AIRFLOW__WEBSERVER__SECRET_KEY={AIRFLOW_SECRET_KEY }
    depends_on:
    - db
    ports:
    - "8080:8080"
    volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - airflow_logs:/opt/airflow/logs
    command: >
      bash -c "airflow db init && airflow webserver & airflow scheduler"

volumes:
  pgdata:
  airflow_logs: