version: '3.9'

services:
  db:
    image: postgres
    container_name: etl_db
    ports:
      - 5432:5432
    volumes:
      - ~/apps/etl_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=etl_password
      - POSTGRES_USER=etl_user
      - POSTGRES_DB=etl_db

volumes:
  pgdata: